CREATE TABLE paises (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,,
    nome varchar(50) NOT NULL,
    sigla2 varchar(2) NOT NULL,
    sigla3 varchar(3) NOT NULL,
    codigo varchar(3) NOT NULL
);

INSERT INTO paises VALUES   
    (NULL, "Afeganistão", "AF", "AFG", "004"),
    (NULL, "África do Sul", "ZA", "ZAF", "710"),
    (NULL, "Albânia", "AL", "ALB", "008"),
    (NULL, "Alemanha", "DE", "DEU", "276"),
    (NULL, "Andorra", "AD", "AND", "020"),
    (NULL, "Angola", "AO", "AGO", "024"),
    (NULL, "Anguilla", "AI", "AIA", "660"),
    (NULL, "Antártida", "AQ", "ATA", "010"),
    (NULL, "Antígua e Barbuda", "AG", "ATG", "028"),
    (NULL, "Antilhas Holandesas", "AN", "ANT", "530"),
    (NULL, "Arábia Saudita", "SA", "SAU", "682"),
    (NULL, "Argélia", "DZ", "DZA", "012"),
    (NULL, "Argentina", "AR", "ARG", "032"),
    (NULL, "Armênia", "AM", "ARM", "51"),
    (NULL, "Aruba", "AW", "ABW", "533"),
    (NULL, "Austrália", "AU", "AUS", "036"),
    (NULL, "Áustria", "AT", "AUT", "040"),
    (NULL, "Azerbaijão", "AZ  ", "AZE", "31"),
    (NULL, "Bahamas", "BS", "BHS", "044"),
    (NULL, "Bahrein", "BH", "BHR", "048"),
    (NULL, "Bangladesh", "BD", "BGD", "050"),
    (NULL, "Barbados", "BB", "BRB", "052"),
    (NULL, "Belarus", "BY", "BLR", "112"),
    (NULL, "Bélgica", "BE", "BEL", "056"),
    (NULL, "Belize", "BZ", "BLZ", "084"),
    (NULL, "Benin", "BJ", "BEN", "204"),
    (NULL, "Bermudas", "BM", "BMU", "060"),
    (NULL, "Bolívia", "BO", "BOL", "068"),
    (NULL, "Bósnia-Herzegóvina", "BA", "BIH", "070"),
    (NULL, "Botsuana", "BW", "BWA", "072"),
    (NULL, "Brasil", "BR", "BRA", "076"),
    (NULL, "Brunei", "BN", "BRN", "096"),
    (NULL, "Bulgária", "BG", "BGR", "100"),
    (NULL, "Burkina Fasso", "BF", "BFA", "854"),
    (NULL, "Burundi", "BI", "BDI", "108"),
    (NULL, "Butão", "BT", "BTN", "064"),
    (NULL, "Cabo Verde", "CV", "CPV", "132"),
    (NULL, "Camarões", "CM", "CMR", "120"),
    (NULL, "Camboja", "KH", "KHM", "116"),
    (NULL, "Canadá", "CA", "CAN", "124"),
    (NULL, "Cazaquistão", "KZ", "KAZ", "398"),
    (NULL, "Chade", "TD", "TCD", "148"),
    (NULL, "Chile", "CL", "CHL", "152"),
    (NULL, "China", "CN", "CHN", "156"),
    (NULL, "Chipre", "CY", "CYP", "196"),
    (NULL, "Cingapura", "SG", "SGP", "702"),
    (NULL, "Colômbia", "CO", "COL", "170"),
    (NULL, "Congo", "CG", "COG", "178"),
    (NULL, "Coréia do Norte", "KP", "PRK", "408"),
    (NULL, "Coréia do Sul", "KR", "KOR", "410"),
    (NULL, "Costa do Marfim", "CI", "CIV", "384"),
    (NULL, "Costa Rica", "CR", "CRI", "188"),
    (NULL, "Croácia (Hrvatska)", "HR", "HRV", "191"),
    (NULL, "Cuba", "CU", "CUB", "192"),
    (NULL, "Dinamarca", "DK", "DNK", "208"),
    (NULL, "Djibuti", "DJ", "DJI", "262"),
    (NULL, "Dominica", "DM", "DMA", "212"),
    (NULL, "Egito", "EG", "EGY", "818"),
    (NULL, "El Salvador", "SV", "SLV", "222"),
    (NULL, "Emirados Árabes Unidos", "AE", "ARE", "784"),
    (NULL, "Equador", "EC", "ECU", "218"),
    (NULL, "Eritréia", "ER", "ERI", "232"),
    (NULL, "Eslováquia", "SK", "SVK", "703"),
    (NULL, "Eslovênia", "SI", "SVN", "705"),
    (NULL, "Espanha", "ES", "ESP", "724"),
    (NULL, "Estados Unidos", "US", "USA", "840"),
    (NULL, "Estônia", "EE", "EST", "233"),
    (NULL, "Etiópia", "ET", "ETH", "231"),
    (NULL, "Fiji", "FJ", "FJI", "242"),
    (NULL, "Filipinas", "PH", "PHL", "608"),
    (NULL, "Finlândia", "FI", "FIN", "246"),
    (NULL, "França", "FR", "FRA", "250"),
    (NULL, "Gabão", "GA", "GAB", "266"),
    (NULL, "Gâmbia", "GM", "GMB", "270"),
    (NULL, "Gana", "GH", "GHA", "288"),
    (NULL, "Geórgia", "GE", "GEO", "268"),
    (NULL, "Gibraltar", "GI", "GIB", "292"),
    (NULL, "Grã-Bretanha (Reino Unido, UK)", "GB", "GBR", "826"),
    (NULL, "Granada", "GD", "GRD", "308"),
    (NULL, "Grécia", "GR", "GRC", "300"),
    (NULL, "Groelândia", "GL", "GRL", "304"),
    (NULL, "Guadalupe", "GP", "GLP", "312"),
    (NULL, "Guam (Território dos Estados Unidos)", "GU", "GUM", "316"),
    (NULL, "Guatemala", "GT", "GTM", "320"),
    (NULL, "Guernsey", "G", "GGY", "832"),
    (NULL, "Guiana", "GY", "GUY", "328"),
    (NULL, "Guiana Francesa", "GF", "GUF", "254"),
    (NULL, "Guiné", "GN", "GIN", "324"),
    (NULL, "Guiné Equatorial", "GQ", "GNQ", "226"),
    (NULL, "Guiné-Bissau", "GW", "GNB", "624"),
    (NULL, "Haiti", "HT", "HTI", "332"),
    (NULL, "Holanda", "NL", "NLD", "528"),
    (NULL, "Honduras", "HN", "HND", "340"),
    (NULL, "Hong Kong", "HK", "HKG", "344"),
    (NULL, "Hungria", "HU", "HUN", "348"),
    (NULL, "Iêmen", "YE", "YEM", "887"),
    (NULL, "Ilha Bouvet (Território da Noruega)", "BV", "BVT", "074"),
    (NULL, "Ilha do Homem", "IM", "IMN", "833"),
    (NULL, "Ilha Natal", "CX", "CXR", "162"),
    (NULL, "Ilha Pitcairn", "PN", "PCN", "612"),
    (NULL, "Ilha Reunião", "RE", "REU", "638"),
    (NULL, "Ilhas Aland", "AX", "ALA", "248"),
    (NULL, "Ilhas Cayman", "KY", "CYM", "136"),
    (NULL, "Ilhas Cocos", "CC", "CCK", "166"),
    (NULL, "Ilhas Comores", "KM", "COM", "174"),
    (NULL, "Ilhas Cook", "CK", "COK", "184"),
    (NULL, "Ilhas Faroes", "FO", "FRO", "234"),
    (NULL, "Ilhas Falkland (Malvinas)", "FK", "FLK", "238"),
    (NULL, "Ilhas Geórgia do Sul e Sandwich do Sul", "GS", "SGS", "239"),
    (NULL, "Ilhas Heard e McDonald (Território da Austrália)", "HM", "HMD", "334"),
    (NULL, "Ilhas Marianas do Norte", "MP", "MNP", "580"),
    (NULL, "Ilhas Marshall", "MH", "MHL", "584"),
    (NULL, "Ilhas Menores dos Estados Unidos", "UM", "UMI", "581"),
    (NULL, "Ilhas Norfolk", "NF", "NFK", "574"),
    (NULL, "Ilhas Seychelles", "SC", "SYC", "690"),
    (NULL, "Ilhas Solomão", "SB", "SLB", "090"),
    (NULL, "Ilhas Svalbard e Jan Mayen", "SJ", "SJM", "744"),
    (NULL, "Ilhas Tokelau", "TK", "TKL", "772"),
    (NULL, "Ilhas Turks e Caicos", "TC", "TCA", "796"),
    (NULL, "Ilhas Virgens (Estados Unidos)", "VI", "VIR", "850"),
    (NULL, "Ilhas Virgens (Inglaterra)", "VG", "VGB", "092"),
    (NULL, "Ilhas Wallis e Futuna", "WF", "WLF", "876"),
    (NULL, "índia", "IN", "IND", "356"),
    (NULL, "Indonésia", "ID", "IDN", "360"),
    (NULL, "Irã", "IR", "IRN", "364"),
    (NULL, "Iraque", "IQ", "IRQ", "368"),
    (NULL, "Irlanda", "IE", "IRL", "372"),
    (NULL, "Islândia", "IS", "ISL", "352"),
    (NULL, "Israel", "IL", "ISR", "376"),
    (NULL, "Itália", "IT", "ITA", "380"),
    (NULL, "Jamaica", "JM", "JAM", "388"),
    (NULL, "Japão", "JP", "JPN", "392"),
    (NULL, "Jersey", "JE", "JEY", "832"),
    (NULL, "Jordânia", "JO", "JOR", "400"),
    (NULL, "Kênia", "KE", "KEN", "404"),
    (NULL, "Kiribati", "KI", "KIR", "296"),
    (NULL, "Kuait", "KW", "KWT", "414"),
    (NULL, "Laos", "LA", "LAO", "418"),
    (NULL, "Látvia", "LV", "LVA", "428"),
    (NULL, "Lesoto", "LS", "LSO", "426"),
    (NULL, "Líbano", "LB", "LBN", "422"),
    (NULL, "Libéria", "LR", "LBR", "430"),
    (NULL, "Líbia", "LY", "LBY", "434"),
    (NULL, "Liechtenstein", "LI", "LIE", "438"),
    (NULL, "Lituânia", "LT", "LTU", "440"),
    (NULL, "Luxemburgo", "LU", "LUX", "442"),
    (NULL, "Macau", "MO", "MAC", "446"),
    (NULL, "Macedônia (República Yugoslava)", "MK", "MKD", "807"),
    (NULL, "Madagascar", "MG", "MDG", "450"),
    (NULL, "Malásia", "MY", "MYS", "458"),
    (NULL, "Malaui", "MW", "MWI", "454"),
    (NULL, "Maldivas", "MV", "MDV", "462"),
    (NULL, "Mali", "ML", "MLI", "466"),
    (NULL, "Malta", "MT", "MLT", "470"),
    (NULL, "Marrocos", "MA", "MAR", "504"),
    (NULL, "Martinica", "MQ", "MTQ", "474"),
    (NULL, "Maurício", "MU", "MUS", "480"),
    (NULL, "Mauritânia", "MR", "MRT", "478"),
    (NULL, "Mayotte", "YT", "MYT", "175"),
    (NULL, "México", "MX", "MEX", "484"),
    (NULL, "Micronésia", "FM", "FSM", "583"),
    (NULL, "Moçambique", "MZ", "MOZ", "508"),
    (NULL, "Moldova", "MD", "MDA", "498"),
    (NULL, "Mônaco", "MC", "MCO", "492"),
    (NULL, "Mongólia", "MN", "MNG", "496"),
    (NULL, "Montenegro", "ME", "MNE", "499"),
    (NULL, "Montserrat", "MS", "MSR", "500"),
    (NULL, "Myanma", "MM", "MMR", "104"),
    (NULL, "Namíbia", "NA", "NAM", "516"),
    (NULL, "Nauru", "NR", "NRU", "520"),
    (NULL, "Nepal", "NP", "NPL", "524"),
    (NULL, "Nicarágua", "NI", "NIC", "558"),
    (NULL, "Níger", "NE", "NER", "562"),
    (NULL, "Nigéria", "NG", "NGA", "566"),
    (NULL, "Niue", "NU", "NIU", "570"),
    (NULL, "Noruega", "NO", "NOR", "578"),
    (NULL, "Nova Caledônia", "NC", "NCL", "540"),
    (NULL, "Nova Zelândia", "NZ", "NZL", "554"),
    (NULL, "Omã", "OM", "OMN", "512"),
    (NULL, "Palau", "PW", "PLW", "585"),
    (NULL, "Panamá", "PA", "PAN", "591"),
    (NULL, "Papua-Nova Guiné", "PG", "PNG", "598"),
    (NULL, "Paquistão", "PK", "PAK", "586"),
    (NULL, "Paraguai", "PY", "PRY", "600"),
    (NULL, "Peru", "PE", "PER", "604"),
    (NULL, "Polinésia Francesa", "PF", "PYF", "258"),
    (NULL, "Polônia", "PL", "POL", "616"),
    (NULL, "Porto Rico", "PR", "PRI", "630"),
    (NULL, "Portugal", "PT", "PRT", "620"),
    (NULL, "Qatar", "QA", "QAT", "634"),
    (NULL, "Quirguistão", "KG", "KGZ", "417"),
    (NULL, "República Centro-Africana", "CF", "CAF", "140"),
    (NULL, "República Democrática do Congo", "CD", "COD", "180"),
    (NULL, "República Dominicana", "DO", "DOM", "214"),
    (NULL, "República Tcheca", "CZ", "CZE", "203"),
    (NULL, "Romênia", "RO", "ROM", "642"),
    (NULL, "Ruanda", "RW", "RWA", "646"),
    (NULL, "Rússia (antiga URSS) - Federação Russa", "RU", "RUS", "643"),
    (NULL, "Saara Ocidental", "EH", "ESH", "732"),
    (NULL, "Saint Vincente e Granadinas", "VC", "VCT", "670"),
    (NULL, "Samoa Americana", "AS", "ASM", "016"),
    (NULL, "Samoa Ocidental", "WS", "WSM", "882"),
    (NULL, "San Marino", "SM", "SMR", "674"),
    (NULL, "Santa Helena", "SH", "SHN", "654"),
    (NULL, "Santa Lúcia", "LC", "LCA", "662"),
    (NULL, "São Bartolomeu", "BL", "BLM", "652"),
    (NULL, "São Cristóvão e Névis", "KN", "KNA", "659"),
    (NULL, "São Martim", "MF", "MAF", "663"),
    (NULL, "São Tomé e Príncipe", "ST", "STP", "678"),
    (NULL, "Senegal", "SN", "SEN", "686"),
    (NULL, "Serra Leoa", "SL", "SLE", "694"),
    (NULL, "Sérvia", "RS", "SRB", "688"),
    (NULL, "Síria", "SY", "SYR", "760"),
    (NULL, "Somália", "SO", "SOM", "706"),
    (NULL, "Sri Lanka", "LK", "LKA", "144"),
    (NULL, "St. Pierre and Miquelon", "PM", "SPM", "666"),
    (NULL, "Suazilândia", "SZ", "SWZ", "748"),
    (NULL, "Sudão", "SD", "SDN", "736"),
    (NULL, "Suécia", "SE", "SWE", "752"),
    (NULL, "Suíça", "CH", "CHE", "756"),
    (NULL, "Suriname", "SR", "SUR", "740"),
    (NULL, "Tadjiquistão", "TJ", "TJK", "762"),
    (NULL, "Tailândia", "TH", "THA", "764"),
    (NULL, "Taiwan", "TW", "TWN", "158"),
    (NULL, "Tanzânia", "TZ", "TZA", "834"),
    (NULL, "Território Britânico do Oceano índico", "IO", "IOT", "086"),
    (NULL, "Territórios do Sul da França", "TF", "ATF", "260"),
    (NULL, "Territórios Palestinos Ocupados", "PS", "PSE", "275"),
    (NULL, "Timor Leste", "TP", "TMP", "626"),
    (NULL, "Togo", "TG", "TGO", "768"),
    (NULL, "Tonga", "TO", "TON", "776"),
    (NULL, "Trinidad and Tobago", "TT", "TTO", "780"),
    (NULL, "Tunísia", "TN", "TUN", "788"),
    (NULL, "Turcomenistão", "TM", "TKM", "795"),
    (NULL, "Turquia", "TR", "TUR", "792"),
    (NULL, "Tuvalu", "TV", "TUV", "798"),
    (NULL, "Ucrânia", "UA", "UKR", "804"),
    (NULL, "Uganda", "UG", "UGA", "800"),
    (NULL, "Uruguai", "UY", "URY", "858"),
    (NULL, "Uzbequistão", "UZ", "UZB", "860"),
    (NULL, "Vanuatu", "VU", "VUT", "548"),
    (NULL, "Vaticano", "VA", "VAT", "336"),
    (NULL, "Venezuela", "VE", "VEN", "862"),
    (NULL, "Vietnã", "VN", "VNM", "704"),
    (NULL, "Zâmbia", "ZM", "ZMB", "894"),
    (NULL, "Zimbábue", "ZW", "ZWE", "716");